# Generated by Django 4.2.5 on 2023-09-07 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='livros',
            old_name='ano_nascimento',
            new_name='ano_publicacao',
        ),
    ]
