# Generated by Django 4.2.5 on 2023-09-07 16:27

from django.db import migrations, models
import livros.models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0002_rename_ano_nascimento_livros_ano_publicacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='livros',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to=livros.models.upload_imagens),
        ),
    ]
